planetxamarin/planetxamarin

- CODE_OF_CONDUCT.md
- src/Firehose.Web/Authors/GeoffreyHuntley.cs
- src/Firehose.Web/Views/Shared/_Layout.cshtml
- changed branding to be PlanetXamarin
- added invitation to send in a pull-request
- added code of conduct
> various changes

- README.md
Include the method that IFilterMyBlogPosts brings in so that the example is clear about where to add the filter logic.
> Improve IFilterMyBlogPosts example code

- src/Firehose.Web/Authors/GeoffreyHuntley.cs
- src/Firehose.Web/Authors/JimBennett.cs
- src/Firehose.Web/Authors/KerryLothrop.cs
- src/Firehose.Web/Firehose.Web.csproj
- src/Firehose.Web/Infrastructure/IAmABlogger.cs
- src/Firehose.Web/Views/WhoAreWe/BusinessCard.cshtml
The Xamarin MVP and Microsoft MVP awards are still separate, so I separated the two interfaces.
> Added Kerry, separated Xamarin and Microsoft MVPs

- src/Firehose.Web/Authors/MarcoKuiper.cs
- src/Firehose.Web/Firehose.Web.csproj
Would be happy to add more Xamarin content to Planet Xamarin!
> Add Marco Kuiper

- README.md
Updated the readme text with explanation about the GravatarHash added in #30 and supplied some sample code for filtering posts. Also added info on the `IAmAXamarinMVP` and `IAmAMicrosoftMVP` interfaces.
> Updated README.md w/ GravatarHash & filter code

- src/Firehose.Web/Authors/AntonioFeregrino.cs
- src/Firehose.Web/Firehose.Web.csproj
Amazing project, I'd like to add myself.
> Add Antonio Feregrino

- src/Firehose.Web/Authors/GregShackles.cs
- src/Firehose.Web/Firehose.Web.csproj
> Add author Greg Shackles

- src/Firehose.Web/Authors/GeertVanDerCruijsen.cs
- src/Firehose.Web/Firehose.Web.csproj
added myself as author in the list
> Added Geert van der Cruijsen as Author

- src/Firehose.Web/Authors/GlennStephens.cs
Added the details for my Xamarin Posts.
> Glenn Stephens added to the list of Authors

- src/Firehose.Web/Web.config
> let's use these rules that were lifted from stackoverflow

- src/Firehose.Web/Web.config
> let's try these ones instead :p

- src/Firehose.Web/Web.config
(If anyone has a better idea how to test this without yolo committing and/or spitting up a virtualmachine/generating ssl cert ugh)
> ugh, this is embarrassing this commit should force ssl

- src/Firehose.Web/Firehose.Web.csproj
And thus were not showing up on the site
> Added two authors who forgot to update the csproj file

- src/Firehose.Web/Content/Site.css
- src/Firehose.Web/Views/Shared/_Layout.cshtml
Some quicker navigation, which collapses into a button on smaller screens
Mucho stylo needed
> Added a menu and some responsiveness

- src/Firehose.Web/Authors/RyanDavis.cs
- src/Firehose.Web/Firehose.Web.csproj
> add rdavisau

- src/Firehose.Web/Authors/MichaelRidland.cs
- src/Firehose.Web/Firehose.Web.csproj
- Blog is active with atleast 3 blog posts in the last 6 months
> Add Michael Ridland

- src/Firehose.Web/Firehose.Web.csproj
- src/Firehose.Web/Views/Preview/Index.cshtml
- src/Firehose.Web/Web.config
- src/Firehose.Web/packages.config
> Humanized Preview dates

- src/Firehose.Web/Controllers/PreviewController.cs
- src/Firehose.Web/Firehose.Web.csproj
- src/Firehose.Web/Infrastructure/CombinedFeedSource.cs
- src/Firehose.Web/ViewModels/PreviewViewModel.cs
- src/Firehose.Web/Views/Preview/Index.cshtml
Did an attempt on showing some blogger info on the Preview page, surely could be optimised but it's a start
> Bring some blogger info on Preview screen

- src/Firehose.Web/Views/Preview/Index.cshtml
The author tag was nog getting filled according to #105. This switches it over to creator instead.
> Moved to creator tag instead of author

- src/Firehose.Web/Authors/StefanDeVogelaere.cs
- src/Firehose.Web/Firehose.Web.csproj
- Blog is active with atleast 3 blog posts in the last 6 months
> Added Stefan de Vogelaere as Author

- src/Firehose.Web/Authors/StevenThewissen.cs
- src/Firehose.Web/Extensions/StringExtensions.cs
- src/Firehose.Web/Firehose.Web.csproj
- src/Firehose.Web/Views/Preview/Index.cshtml
Started cleaning up the content that is being pulled in as HTML inside the Preview page. Also fixed my own profile.
> Cleanup preview

- src/Firehose.Web/Authors/GeraldVersluis.cs
- src/Firehose.Web/Views/Preview/Index.cshtml
Improved getting the name of the author on the preview page and filled in the blanks for my author profile
> Improved authorname preview

- src/Firehose.Web/Authors/EstebanSolano.cs
- src/Firehose.Web/Firehose.Web.csproj
- Blog is active with at least 3 blog posts in the last 6 months
> Add Esteban Solano

- src/Firehose.Web/Authors/AlmirVuk.cs
- src/Firehose.Web/Firehose.Web.csproj
- Blog is active with atleast 3 blog posts in the last 6 months
> Added AlmirVuk.cs

- src/Firehose.Web/Authors/LiXiaobin.cs
- src/Firehose.Web/Firehose.Web.csproj
Thank you !  
I want to learn more about it.
> Add Lixiaobin author from China

- src/Firehose.Web/Authors/CorradoCavalli.cs
- src/Firehose.Web/Firehose.Web.csproj
Hi all,
I've added myself as author, hope everything is ok :-)
Cheers
/C.
> Added Corrado Cavalli as author.

- src/Firehose.Web/Authors/NigelSampson.cs
- src/Firehose.Web/Firehose.Web.csproj
- Blog is active with atleast 3 blog posts in the last 6 months
> Create author for Nigel Sampson

- src/Firehose.Web/Authors/EnricoRossini.cs
- src/Firehose.Web/Firehose.Web.csproj
- Blog is active with atleast 3 Xamarin related blog posts in the last 6 months
> Add a new author

- src/Firehose.Web/Views/Authors/List.cshtml
- src/Firehose.Web/Views/Authors/Map.cshtml
Search is cleared when a map pin is clicked, bit of styling as well
> Tweaks for searchbar

- src/Firehose.Web/Authors/ThomasLebrun.cs
- src/Firehose.Web/Firehose.Web.csproj
- Blog is active with atleast 3 Xamarin related blog posts in the last 6 months
> ThomasLebrun.cs: Author created

- src/Firehose.Web/Authors/DanRigby.cs
> Remove "at Microsoft" for Dan Rigby

- src/Firehose.Web/Authors/MalcolmJack.cs
- src/Firehose.Web/Firehose.Web.csproj
Submit new author - Malcolm Jack
- Blog is active with atleast 3 Xamarin related blog posts in the last 6 months
> Submit Community Author - Malcolm Jack

- src/Firehose.Web/Controllers/FeedController.cs
Catching Exception at a higher level and return the orginal feed if an Exception occurs
> Attempt to make getting feeds bit more robust

- src/Firehose.Web/Authors/ChrisRiesgo.cs
- src/Firehose.Web/Firehose.Web.csproj
> Chris Riesgo standing by

- src/Firehose.Web/Authors/ThomasBurkhart.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added my blog Guru Meditation

- src/Firehose.Web/Authors/JanTourlamain.cs
- src/Firehose.Web/Firehose.Web.csproj
> Request for adding blog to PlanetXamarin

- src/Firehose.Web/Authors/WilliamRodriguez.cs
> Added short bio and github handle.

- src/Firehose.Web/Authors/FabioCozzolino.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added Fabio Cozzolino as author

- src/Firehose.Web/Authors/TimotheLariviere.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added new author

- src/Firehose.Web/Infrastructure/CombinedFeedSource.cs
Added some simple logic to check if a feed is available and returns an a-ok!
With this the dummy variable seems redundant.
As per #169 love to hear your thoughts!
> Loadingfeed enhancing

- src/Firehose.Web/Authors/DileepaRajapaksa.cs
- src/Firehose.Web/Firehose.Web.csproj
> I have added my blog !

- README.md
Fix minor spacing error on `README.md`.
> Fix Spacing

- src/Firehose.Web/Authors/ThomasBandt.cs
- src/Firehose.Web/Firehose.Web.csproj
> Adds profile for Thomas Bandt

- README.md
This request removes the MVP awarded dates, and also includes the GitHubHandle in the examples.
> cleanup code examples

- src/Firehose.Web/Authors/MarioGalvan.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added myself.

- src/Firehose.Web/Authors/AlexDunn.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added Alex Dunn to authors

- src/Firehose.Web/Authors/DiegoPonceDeLeon.cs
- src/Firehose.Web/Firehose.Web.csproj
> Add DiegoPonceDeLeon

- src/Firehose.Web/Authors/KerryLothrop.cs
> Fixed feed URL to provide the English language feed

- src/Firehose.Web/Authors/MFractor.cs
- src/Firehose.Web/Firehose.Web.csproj
> Add MFractor as a feed author

- src/Firehose.Web/Authors/JunianTriajianto.cs
- src/Firehose.Web/Firehose.Web.csproj
> Add Junian Triajianto Author

- src/Firehose.Web/Authors/ChrisRiesgo.cs
- src/Firehose.Web/Firehose.Web.csproj
> Adding Chris Riesgo back

- src/Firehose.Web/Firehose.Web.csproj
> Remove HumbertoJaimes as feed is messed up

- src/Firehose.Web/Authors/MatthewSoucoup.cs
> Updating Matt Soucoup's GitHub handle & filter

- src/Firehose.Web/Authors/TomaszCielecki.cs
> Added MS MVP interface to myself

- src/Firehose.Web/Authors/PieterNijs.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added profile

- src/Firehose.Web/Authors/WinstonGubantes.cs
- src/Firehose.Web/Firehose.Web.csproj
> added new author (Winston Gubantes) from davao philippines

- src/Firehose.Web/Authors/BryanAnthonyGarcia.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added myself (BryanAnthonyGarcia.cs) to the list of Planet Xamarin authors

- src/Firehose.Web/Authors/VulcanLee.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added myself (VulcanLee.cs) to the list of Planet Xamarin authors

- src/Firehose.Web/Authors/VulcanLee.cs
Because my Gravatar picture cannot show on Planet Xamarin web page, I need change my email address.
> Change my Email address

- src/Firehose.Web/Authors/DanSiegel.cs
- src/Firehose.Web/Firehose.Web.csproj
> Add Author Dan Siegel

- src/Firehose.Web/Authors/StevenThewissen.cs
> Alter my own data to match the new stuff.

- src/Firehose.Web/Authors/BryanAnthonyGarcia.cs
- src/Firehose.Web/Firehose.Web.csproj
> Changed my Bio because it ruins the layout

- src/Firehose.Web/Authors/TimKlingeleers.cs
- src/Firehose.Web/Firehose.Web.csproj
> Add Tim Klingeleers as an author

- src/Firehose.Web/Authors/JohnWilson.cs
- src/Firehose.Web/Firehose.Web.csproj
> Add John Wilson as author

- src/Firehose.Web/Authors/MartynWiggins.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added Martynnw

- src/Firehose.Web/Authors/RamonEsteban.cs
- src/Firehose.Web/Firehose.Web.csproj
> New Author request: Ramon Esteban

- src/Firehose.Web/Authors/SamDebruyn.cs
- src/Firehose.Web/Firehose.Web.csproj
No filter is applied as the feed URL already contains a tag-based filter.
I know the activity on my blog could be better, but I have a few new Xamarin blogposts planned for the coming weeks so that's why I am adding myself to the list.
> add Sam Debruyn as community member

- src/Firehose.Web/Authors/JunianTriajianto.cs
> Update JunianTriajianto.cs short bio

- src/Firehose.Web/Authors/JesseLiberty.cs
> Added using statements and renamed file to jesseliberty.cs

- src/Firehose.Web/Authors/JesseLiberty.cs
- src/Firehose.Web/Firehose.Web.csproj
Fixed code in class and added to csproj
> Attempt to fix Jesse

- src/Firehose.Web/Authors/CarelLotz.cs
- src/Firehose.Web/Firehose.Web.csproj
> add CarelLotz as author

- src/Firehose.Web/Authors/AshanDhanapala.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added Ashan Dhanapala as a author and new file added

- src/Firehose.Web/Authors/Xablu.cs
- src/Firehose.Web/Firehose.Web.csproj
> introduce Xablu

- src/Firehose.Web/Authors/JanTourlamain.cs
updated website URI to use https
> updated author file jantourlamain to use https urls

- src/Firehose.Web/Authors/BartoszRadlak.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added new author from Poland ( BartoszRadlak )

- src/Firehose.Web/Authors/NigelFerrissey.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added NigelFerrissey to authors.

- .github/PULL_REQUEST_TEMPLATE.md
Added one about new blogs, I've seen a couple being submitted with the exact three posts that are needed. To prevent blogs being added, that are started and never looked at ever again, there is now a rule that it has to be active for at least a year. But maybe that is a bit much? What do you guys think?
> Sharpened the rules a bit to make it more clear.

- src/Firehose.Web/Authors/AlmirVuk.cs
> Added https urls to my Blog info

- src/Firehose.Web/Authors/DanRigby.cs
* Change website url to use https
* Existing http url was redirecting to https anyway
* Update profile information to be more current
> Update profile information and website url for Dan Rigby

- src/Firehose.Web/Authors/StefanRiedmann.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added Stefan Riedmann

- src/Firehose.Web/Authors/RendyDelRosario.cs
> Updated to HTTPS Urls & Bio

- src/Firehose.Web/Authors/MergeConflict.cs
> Use HTTPS for merge conflict

- src/Firehose.Web/Authors/AdamPatridge.cs
Seems I missed an important part of the filtering system (see #341). Rather than spam the Xamarin world with any further Netduino posts, I figured I should fix that.
> Actually enable filtering on my blog posts.

- src/Firehose.Web/Authors/KymPhillpotts.cs
Updated HTTPS, Gravater, github
> Updated details - kym phillpotts

- src/Firehose.Web/Authors/SvenMichaelStuebe.cs
- Change website url to use https
- Update profile information to be more current
#334
> Sven-Michael Stübe HTTPS update

- src/Firehose.Web/Authors/JonDick.cs
> Switch redth.codes to https

- src/Firehose.Web/Authors/AdamPatridge.cs
> Update patridgedev.com URLs to HTTPS

- .github/PULL_REQUEST_TEMPLATE.md
…per #334
Just noticed that the new HTTPS requirement could be mentioned for incoming blogs and wanted to get the ball rolling. Feel free to edit the wording as desired.
> Update PR template with new HTTPS requirement

- src/Firehose.Web/Authors/MFractor.cs
> Update MFractor feeds and product description

- src/Firehose.Web/Authors/KerryLothrop.cs
> Updated to HTTPS for kerry.lothrop.de (#334).

- src/Firehose.Web/Authors/MFractor.cs
> Change MFractors 'feature-focus' feed to the 'learn' feed.

- src/Firehose.Web/Authors/ElbrinnerDaSilvaFernandes.cs
- src/Firehose.Web/Firehose.Web.csproj
> add new user: elbrinner

- src/Firehose.Web/Authors/MarkoLazic.cs
- src/Firehose.Web/Firehose.Web.csproj
> Request to be added as author (MarkoLazic)

- src/Firehose.Web/Authors/TimotheLariviere.cs
I've added HTTPS support for my blog.
> Updated TimotheLariviere to SSL

- src/Firehose.Web/Authors/GlennStephens.cs
> Updates Blog Uri, GitHub handle and Email for Glenn Stephens

- src/Firehose.Web/Authors/JonPeppers.cs
I also updated my bio, I work for Microsoft/Xamarin now
Applies to #334
> Use HTTPS for jonathanpeppers.com

- src/Firehose.Web/Authors/MichaelRidland.cs
> Update Michael Ridland SSL and Microsoft MVP

- src/Firehose.Web/Authors/GoneMobile.cs
> Updated email address for GoneMobile

- src/Firehose.Web/Authors/DamianMehers.cs
Updating my blog URL to https://damian.fyi/
> Moved blog site to https://damian.fyi/

- src/Firehose.Web/Authors/WilliamBarbosa.cs
- src/Firehose.Web/Firehose.Web.csproj
:tada: 
*I recently migrated my blog from github pages to medium, hence why there aren't many older blog posts there. I, however, am very much active 😄
> Add William Barbosa as an author

- src/Firehose.Web/Authors/DanielCauser.cs
- src/Firehose.Web/Firehose.Web.csproj
> Request to be added as author (DanielCauser)

- src/Firehose.Web/Authors/DevlinDuldulao.cs
> Update ShortBioOrTagLine and use IAmACommunityMember

- src/Firehose.Web/Infrastructure/CombinedFeedSource.cs
Fixes TSL 1.2 feeds not working throwing AuthenticationException.
> Fix #389 TLS 1.2 feeds not working.

- src/Firehose.Web/Authors/DanSiegel.cs
Updating Bio
Adding Twitter Handle
> updating profile

- src/Firehose.Web/Authors/MahmoudAli.cs
Double checked the blog feed and noticed the filter wasn't working correctly.
> Fix Mahmoud Ali author filter

- src/Firehose.Web/Authors/SaturninoPimentel.cs
- src/Firehose.Web/Firehose.Web.csproj
> SaturninoPimentel.cs added

- src/Firehose.Web/Authors/OfficialXamarinBlog.cs
- src/Firehose.Web/Infrastructure/CombinedFeedSource.cs
> Use default filter if not implementing IFilterMyBlogPosts

- src/Firehose.Web/Authors/SebastianJensen.cs
Updating the description of my profile, because the name was inserted automatically.
> Fix description for Sebastian Jensen

- src/Firehose.Web/Authors/CharlinAgramonte.cs
- src/Firehose.Web/Firehose.Web.csproj
> Adding Xamgirl Blog

- src/Firehose.Web/Firehose.Web.csproj
Got removed somehow. Probably in a merge.
> Add back Daniel Causer

- appveyor.yml
- build.cake
- src/Firehose.Web/Authors/AlejandroRuiz.cs
- src/Firehose.Web/Authors/AlexandrSorokoletov.cs
- src/Firehose.Web/Authors/ChrisRiesgo.cs
- src/Firehose.Web/Authors/ChrisWilliams.cs
- src/Firehose.Web/Authors/DavidBritch.cs
- src/Firehose.Web/Authors/DevlinDuldulao.cs
- src/Firehose.Web/Authors/GeertVanDerCruijsen.cs
- src/Firehose.Web/Authors/GlennStephens.cs
- src/Firehose.Web/Authors/GregShackles.cs
- src/Firehose.Web/Authors/JanTourlamain.cs
- src/Firehose.Web/Authors/JohnMiller.cs
- src/Firehose.Web/Authors/JonDick.cs
- src/Firehose.Web/Authors/JonPeppers.cs
- src/Firehose.Web/Authors/KymPhillpotts.cs
- src/Firehose.Web/Authors/MarioGalvan.cs
- src/Firehose.Web/Authors/MatthewLeibowitz.cs
- src/Firehose.Web/Authors/NigelFerrissey.cs
- src/Firehose.Web/Authors/RamonEsteban.cs
- src/Firehose.Web/Authors/RendyDelRosario.cs
- src/Firehose.Web/Authors/Suthahar.cs
- src/Firehose.Web/Authors/TomSoderling.cs
- src/Firehose.sln
- src/UnitTest/AuthorsTest.cs
- src/UnitTest/UnitTest.csproj
Adds Unit Tests which currently ensures:
- Authors need to be in the "Firehose.Web.Authors" namespace
- Authors need to implement the `IAmACommunityMember` interface or a derivative
> Unit tests

- src/Firehose.Web/Authors/MalcolmJack.cs
- src/Firehose.Web/Authors/VulcanLee.cs
- src/Firehose.Web/Extensions/SyndicationItemExtensions.cs
- src/Firehose.Web/Firehose.Web.csproj
- src/Firehose.Web/Infrastructure/CombinedFeedSource.cs
- Moves default filter out into extension so it can be used for cases where Authors implement `IFilterMyBlogPosts`
- Applies extension code where applicable
- Disables "Daily Links" posts from @InquisitorJax as we are not interested in those
> No daily links 

- src/Firehose.Web/Extensions/GravatarHashingExtensions.cs
- src/Firehose.Web/Extensions/Md5HashingExtensions.cs
- src/Firehose.Web/Extensions/StringExtensions.cs
- src/Firehose.Web/Firehose.Web.csproj
- src/Firehose.Web/Views/Authors/BusinessCard.cshtml
- src/UnitTest/StringExtensionsTest.cs
- src/UnitTest/SyndicationItemExtensionsTest.cs
- src/UnitTest/UnitTest.csproj
Added some more unit tests to test some of our infrastructure and extension methods.
> Infrastructure unit tests

- src/Firehose.Web/Authors/EvgenyZborovsky.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **https://smellyc0de.wordpress.com/**: 
:scroll: **https://smellyc0de.wordpress.com/tag/xamarin-forms/feed/**: 
> Adding smellyc0de blog

- src/Firehose.Web/Authors/MartinZikmund.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://blog.mzikmund.com/
:scroll: **Feed Url**: https://blog.mzikmund.com/feed/?lang=en_us
> Added Martin Zikmund

- src/Firehose.Web/Authors/DanielHindrikes.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://Danielhindrikes.se
:scroll: **Feed Url**: https://danielhindrikes.se/index.php/feed/
> Added Daniel Hindrikes

- src/Firehose.Web/Authors/MarkAllibone.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: [https://mallibone.com](https://mallibone.com)
:scroll: **Feed Url**: [https://mallibone.com/feed/](https://mallibone.com/feed/)
> Added Mark Allibone

- src/Firehose.Web/Authors/MarcioCampos.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: <https://portalxamarin.com.br/>
:scroll: **Feed Url**: <https://portalxamarin.com.br/feed>
> * added Marcio Campos

- src/Firehose.Web/Authors/JeromeGiacomini.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://jeromegiacomini.net/Blog/
:scroll: **Feed Url**:  https://jeromegiacomini.net/Blog/feed/
> Added Jérôme Giacomini

- src/Firehose.Web/Authors/HussainAbbasi.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://www.intelliabb.com
:scroll: **Feed Url**: https://www.intelliabb.com/feed
> Added Hussain Abbasi as author

- src/Firehose.Web/Authors/JasonDeBoever.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://thisoldbrain.com/
:scroll: **Feed Url**: https://thisoldbrain.com/rss
> Added Jason DeBoever

- src/Firehose.Web/Authors/LuisBeltran.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://luisbeltran.mx
:scroll: **Feed Url**: https://luisbeltran.mx/feed/
> New Author: Luis Beltran

- src/Firehose.Web/Authors/TrailheadTechnology.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://trailheadtechnology.com/blog
:scroll: **Feed Url**: https://trailheadtechnology.com/feed
> Added Trailhead Technology

- .gitignore
- src/Firehose.Web/Authors/MFractor.cs
Also add mfractors working directory to gitignore
> Remove empty MFractor feeds.

- src/Firehose.Web/Authors/DanielHindrikes.cs
- src/Firehose.Web/Authors/GlennStephens.cs
- src/Firehose.Web/Firehose.Web.csproj
- src/Firehose.Web/Infrastructure/CombinedFeedSource.cs
- src/Firehose.Web/Properties/AssemblyInfo.cs
- src/UnitTest/AuthorsTest.cs
- src/UnitTest/UnitTest.csproj
Adds more integration tests against Author feeds.
The tests now fetch the feeds and checks whether they contain items.
> Integration tests

- src/Firehose.Web/Authors/StephenMarcus.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: http://www.marcusts.com
:scroll: **Feed Url**: http://www.marcusts.com/category/xamarin/feed
> New Author: Stephen Marcus

- src/Firehose.Web/Authors/JohnThiriet.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://johnthiriet.com/
:scroll: **Feed Url**: https://johnthiriet.com/feed.xml
> Add new author John Thiriet

- src/Firehose.Web/Authors/MartijnVanDijk.cs
:pencil2: **Blog Url**: https://medium.com/@martijn00
:scroll: **Feed Url**: https://medium.com/feed/@martijn00
> Update information for Martijn van Dijk

- src/Firehose.Web/Authors/MartijnVanDijk.cs
> Fix double mvp status

- src/Firehose.Web/Firehose.Web.csproj
Feed is empty. @marciovcampos @leonardoCarmonio @dayaneLima
> Portal Xamarin returns empty feed

- src/Firehose.Web/Firehose.Web.csproj
Reverts planetxamarin/planetxamarin#484 as @therealjohn claims the issue is fixed!
> Revert "Removed John Miller due to expired SSL"

- src/Firehose.Web/Authors/JeffersonBalivo.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://balivo.com.br
:scroll: **Feed Url**: https://balivo.com.br/feed/
> Add author: JeffersonBalivo

- src/Firehose.Web/Authors/DevlinDuldulao.cs
> Fixed double 'a Microsoft MVP' description

- src/Firehose.Web/Extensions/SyndicationItemExtensions.cs
> Fixes #512 Check for podcast keywords

- src/Firehose.Web/Authors/JacobDuijzer.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**:  https://blog.duijzer.com/
:scroll: **Feed Url**: https://blog.duijzer.com/index.xml
> Added myself as an author

- src/Firehose.Web/Extensions/SyndicationItemExtensions.cs
Allow checks for both keywords and categories to have effect.
> Split keywords into own check

- src/Firehose.Web/Authors/JeanMarieAlfonsi.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://www.sharpnado.com/
:scroll: **Feed Url**: https://www.sharpnado.com/rss/
> Added jean-marie alfonsi as Author

- src/Firehose.Web/Authors/GeertVanDerCruijsen.cs
- src/Firehose.Web/Firehose.Web.csproj
- src/Firehose.sln
This reverts commit ab9e49e41348823249dd8a517039ccbed1177aa5.
The other PR had messed up history. Rebased on master
> Revert "Remove @geertvdc (#523)"

- src/Firehose.Web/Authors/EvgenyZborovsky.cs
> Update author information: Evgeny Zborovsky.

- src/Firehose.Web/Authors/JulianoCustodio.cs
Update StateOrRegion, ShortBioOrTagLine and Position.
> Update info author Juliano Custódio

- src/Firehose.Web/Authors/LuisPujols.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added Luis Pujols as author

- src/Firehose.Web/Authors/LuisPujols.cs
- src/Firehose.Web/Firehose.Web.csproj
Updated the shortBio for the author, since it included it's name on the bio and made it look like it was duplicated.
Bio read on Planet Xamarin Before:
"Luis Pujols Luis Pujols is a Software Engineer ".
Now it should be:
"Luis Pujols is a Software Engineer"
> Fix Duplicated name on ShortBio for author "Luis Pujols"

- src/Firehose.Web/Authors/DanielMonetelli.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **youtube channel Url**: https://www.youtube.com/c/danielmonetelli
:scroll: **Feed Url**: https://www.youtube.com/feeds/videos.xml?channel_id=UCTAlbAORoFvAHj7jA4DLSFQ
> PR Daniel Monetelli

- src/Firehose.Web/Authors/JohnTaubensee.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://taubensee.net
:scroll: **Feed Url**: https://taubensee.net/rss
> Adding John Taubensee

- src/Firehose.Web/Authors/JesseJiang.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://jessejiang.xyz/
:scroll: **Feed Url**: https://jessejiang.xyz/feed/
> Add jesse jiang

- src/Firehose.Web/Authors/AndrewHoefling.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://www.andrewhoefling.com
* https://www.andrewhoefling.com/feed.xml
* https://www.andrewhoefling.com/feed.xml?category=xamarin
My blog is *not* only Xamarin. I configured the RSS feed to display only xamarin content …
> Added Andrew Hoefling

- src/Firehose.Web/Authors/KodjoLaurentEgbakou.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://lioncoding.com
:scroll: **Feed Url**:  https://lioncoding.com/feed.xml
**Notes**
My blog is only about Xamarin.
> Added Kodjo Laurent Egbakou

- src/Firehose.Web/Authors/OfficialXamarinBlog.cs
- src/Firehose.Web/Authors/Suthahar.cs
- src/Firehose.Web/Authors/TheXamarinShow.cs
- src/Firehose.Web/Views/Preview/Index.cshtml
> Update xamarin blog url, fix matching for author.

- src/Firehose.Web/Authors/MikolajKieres.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: http://progrunning.net/
:scroll: **Feed Url**: http://progrunning.net/rss
> Adding Mikolaj Kieres as author

- src/Firehose.Web/Authors/UmairHassan.cs
- src/Firehose.Web/Firehose.Web.csproj
- src/UnitTest/AuthorsTest.cs
- [✓] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [✓] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [✓ ] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [✓ ] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [✓ ] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in …
> Umair Hassan Author added

- src/Firehose.Web/Authors/DivikiranRavela.cs
- src/Firehose.Web/Firehose.Web.csproj
Divikiran Ravela file to join Planet Xamarin
:pencil2: **Blog Url**: https://xamlabs.com/
:scroll: **Feed Url**: https://xamlabs.com/feed/
> Divikiran Ravela file to join Planet Xamarin

- src/Firehose.Web/Authors/SheharyarShahid.cs
- src/Firehose.Web/Firehose.Web.csproj
> Added Sheharyar Shahid as author

- src/Firehose.Web/Authors/BenceLenart.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://officialdoniald.azurewebsites.net/
:scroll: **Feed Url**: https://officialdoniald.azurewebsites.net/feed/
> Adding Bence

- src/Firehose.Web/Authors/DanSiegel.cs
- src/Firehose.Web/Authors/Syncfusion.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://www.syncfusion.com/blogs/
:scroll: **Feed Url**: https://www.syncfusion.com/blogs/feed
> Adding Syncfusion Xamarin blogs.

- src/Firehose.Web/Authors/SamirGC.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**:  http://xamaringuyshow.com/
:scroll: **Feed Url**: http://xamaringuyshow.com/feed
> XamarinPlanetBlogAuthor

- src/Firehose.Web/Authors/BrandonMinnick.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://codetraveler.io
:scroll: **Feed Url**: https://codetraveler.io/tag/xamarin/rss/
> Added Brandon Minnick

- src/Firehose.Web/Authors/MattCrombie.cs
- src/Firehose.Web/Firehose.Web.csproj
> Add Matt Crombie to authors

- src/Firehose.Web/Authors/MattCrombie.cs
- src/Firehose.Web/Firehose.Web.csproj
> Updating GravatarHash to lowercase because upper apparently doesn't work

- src/Firehose.Web/Authors/RunarOvesenHjerpbakk.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: https://hjerpbakk.com
:scroll: https://hjerpbakk.com/feed.xml
- [ X] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [ X] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [ X] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [ X] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [ X] I have applied a filter (Optional: if blog is only about Xamarin …
> Added Runar Ovesen Hjerpbakk

- src/Firehose.Web/Authors/LogeshPalani.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://logeshpalani.blogspot.com/
:scroll: **Feed Url**: https://logeshpalani.blogspot.com/feeds/posts/default
> Added Logesh Palani

- src/Firehose.Web/Authors/MFractor.cs
> Update MFractor location, contact email and bio.

- src/Firehose.Web/Authors/AndreasNesheim.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://www.andreasnesheim.no/
:scroll: **Feed Url**: https://www.andreasnesheim.no/feed
> Added Andreas Nesheim as contributor

- src/Firehose.Web/Authors/AndrewHoefling.cs
Minor update to my existing profile, to document that I am now a Microsoft MVP
> Updated profile to show Microsoft MVP award

- src/Firehose.Web/Authors/Xablu.cs
> Fix Xablu's language

- src/Firehose.Web/Authors/RicardoPrestes.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://oficinadologan.wordpress.com/
:scroll: **Feed Url**: https://oficinadologan.wordpress.com/rss
> Adding author

- src/Firehose.Web/Authors/MFractor.cs
> Filter out Visual Studio extensibility blogs for MFractor.

- src/Firehose.Web/Authors/BohdanBenetskyi.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://medium.com/@benetskyybogdan/
:scroll: **Feed Url**: https://medium.com/feed/@benetskyybogdan/
> Add Bohdan Benetskyi as an Author

- src/Firehose.Web/Authors/BoguslawBlonski.cs
- src/Firehose.Web/Firehose.Web.csproj
✏️ Blog Url: https://medium.com/@boguslawblonski/
📜 Feed Url: https://medium.com/feed/@boguslawblonski/
I have a valid blog & RSS URL, both using HTTPS 🔒 with a valid certificate
I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
My blog is active with at least 3 Xamarin related blog posts in the last 6 months
In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
I have applied a filter (Optional: if blog is only about Xamarin or you …
> Add Boguslaw Blonski as author

- src/Firehose.Web/Authors/AchrafBenAlaya.cs
> update website (old is down)

- src/Firehose.Web/Authors/AlmirVuk.cs
Changes are: 
- New blogRL, 
- Short Bio text, 
- New RSS URL and 
- IamMicrosoftMVP interface implemented
:pencil2: **Blog Url**: https://almirvuk.com/
:scroll: **Feed Url**: https://almirvuk.com/rss
> Changes on existing Author (new blog url and rss feed)

- src/Firehose.Web/Authors/Suthahar.cs
I have upgraded my blog website so Updated Blog ulr  and feed url
> Updated Blog ulr  and feed url

- src/Firehose.Web/Authors/DamianMehers.cs
> Update my feed URL: I've moved to GitHub pages

- src/Firehose.Web/Authors/AlexShirshov.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://omnitalented.com
:scroll: **Feed Url**: https://omnitalented.com/rss-xamarin.xml
> Added an author: Alex Shirshov

- src/Firehose.Web/Authors/DenysFiediaiev.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://medium.com/@prin53
:scroll: **Feed Url**: https://medium.com/feed/@prin53
> Add Denys Fiediaiev author

- src/Firehose.Web/Authors/FelipeBaltazar.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://medium.com/@felipedasilvabaltazar
:scroll: **Feed Url**: https://medium.com/feed/@felipedasilvabaltazar
> Added Felipe Baltazar as author

- src/Firehose.Web/Authors/StevenCheco.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://checox.com 
:scroll: **Feed Url**: https://checox.com/feed
> Add Steven Checo Profile

- src/Firehose.Web/Authors/SylvainMoingeon.cs
:pencil2: **Blog Url**: https://www.sylvainmoingeon.fr/
:scroll: **Feed Url**: https://www.sylvainmoingeon.fr/feed.xml
- [x ] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [x ] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x ] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x ] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [x ] I have added my …
> Add Sylvain Moingeon

- src/Firehose.Web/Authors/JohannWeiher.cs
- src/Firehose.Web/Firehose.Web.csproj
https://maui-blog.com
https://maui-blog.com/feed/
> JohannWeiher added

- src/Firehose.Web/Authors/DamienDoumer.cs
I updated my description and added the RSS feed of my youtube channel to my Author's class.
> Added my youtube channel's RSS feed

- src/Firehose.Web/Authors/SylvainMoingeon.cs
- src/Firehose.Web/Firehose.Web.csproj
Ok, I have :
- Added missing author file in csproj file
- Removed unused Filter (badly commented and throwing exception)
> Fix SylvainMoingeon

- src/Firehose.Web/Authors/BradDean.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://truegeek.com
:scroll: **Feed Url**: https://truegeek.com/feed.xml
> Adding new author Brad Dean

- src/Firehose.Web/Authors/DylanBerry.cs
> Updated feeduris for dylanberry.com

- src/Firehose.Web/Authors/MarkAllibone.cs
As kindly pointed out in #719 by @saamerm.
> Fix broken RSS feed

- src/Firehose.Web/Authors/AllanRitchie.cs
Moving blog
- [] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in the title or categories in your blog posts)
Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your blog are too significant to be fixed within a …
> Update AllanRitchie Details

- src/Firehose.Web/Authors/VijayAnandEG.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://egvijayanand.in/
:scroll: **Feed Url**: https://egvijayanand.in/feed/
> Added author profile - Vijay Anand E G

- src/Firehose.Web/Authors/Suthahar.cs
> Updated Video Url

- src/Firehose.Web/Authors/DaveMurray.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://blog.taranissoftware.com/
:scroll: **Feed Url**: https://blog.taranissoftware.com/rss.xml
> Added author Dave Murray

- src/Firehose.Web/Authors/GlennVersweyveld.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **https://blog.depechie.com**: 
:scroll: **https://blog.depechie.com/index.xml**: 
> Added author Glenn Versweyveld

- src/Firehose.Web/Authors/JuanSturla.cs
- src/Firehose.Web/Firehose.Web.csproj
FeedLanguageCode is "es" for my main blog, but I also added a FeedUri for it's english version.
:pencil2: **Blog Url**:  
🇪🇸  https://pollitosdemaui.wordpress.com/ 
🇺🇸 https://mauichicken.wordpress.com/
:scroll: **Feed Url**:  
🇪🇸  https://pollitosdemaui.wordpress.com/category/net-maui/feed/  
🇺🇸  https://mauichicken.wordpress.com/category/net-maui/feed/
Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is …
> JuanSturla Author added

- src/Firehose.Web/Authors/TobyField.cs
- src/Firehose.Web/Firehose.Web.csproj
> Add Toby Field to authors

- src/Firehose.Web/Authors/Respawnsive.cs
- src/Firehose.Web/Firehose.Web.csproj
:pencil2: **Blog Url**: https://www.respawnsive.com/category/xamarin-en/
:scroll: **Feed Url**: https://www.respawnsive.com/category/xamarin-en/feed/
Well I'm about writing a series called Playground and playing with MS DI extensions with Xamarin.Forms, Prism, Shiny & ReactiveUI. It's clearly not a 3 posts guideline compliance try, as many others will follow about Playground, but also my OSS libs like Apizr or Localizr or some others. The small amount of time is due to local covid lock down offering some time to write things, hosted by my current employer web site. But I'm not really new on the blogging planet as you can see on my first blog …
> Add Respawnsive

- src/Firehose.Web/Firehose.Web.csproj
- src/Firehose.Web/Infrastructure/NewCombinedFeedSource.cs
- src/UnitTest/UnitTest.csproj
Enable support for TLS 1.3 (for hosts that do not support TLS 1.2 or TLS 1.1)
> Enable TLS 1.3

- src/Firehose.Web/Authors/AndrasToth.cs
> Moved banditoth.hu to banditoth.net

- src/Firehose.WebCore/Infrastructure/RssFeedResult.cs
Fix for warning about sync over async
> Convert RssFeedResult to async

- src/Firehose.WebCore/Controllers/PreviewController.cs
- src/Firehose.WebCore/Extensions/GravatarHashingExtensions.cs
- src/Firehose.WebCore/Firehose.WebCore.csproj
- src/Firehose.WebCore/Infrastructure/NewCombinedFeedSource.cs
- src/Firehose.WebCore/Infrastructure/RssFeedResult.cs
- src/Firehose.WebCore/Program.cs
- src/Firehose.WebCore/ViewModels/PreviewViewModel.cs
- src/Firehose.WebCore/Views/Authors/BusinessCard.cshtml
- src/Firehose.WebCore/Views/Authors/ProfileCard.cshtml
- src/Firehose.WebCore/Views/Home/PodcastCard.cshtml
- src/Firehose.WebCore/web.config
- src/Firehose.sln
- src/UnitTest/AuthorsTest.cs
- src/UnitTest/UnitTest.csproj
This PR removes final .NET Framework dependencies to complete the ASP.NET Core migration.
- Removes SystemWebAdapters dependency
- Converts config from .NET Framework ConfigurationManager to IConfiguration
- Updates Unit Tests
- Points Unit Test project at ASP.NET Core project
> Remove final .NET Framework dependencies
